
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-09
owner: ucsb-cs156-s25
repo_name: team01-s25-09
pull_requests: [{"author":{"id":"U_kgDOB3DxTg","is_bot":false,"login":"moiez12","name":""},"headRefName":"MB-GetEndpointSingleRecord","number":62,"title":"MB - add GET (show) endpoint for a single record in Articles table","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/62"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-recreq4","number":61,"title":"AK - PUT(edit/delete) to Controller for the RecommendationRequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/61"},{"author":{"id":"U_kgDOCMMDPQ","is_bot":false,"login":"jasozh5","name":""},"headRefName":"jz-createMenuItemReviewController","number":60,"title":"Jz create menu item review controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/60"},{"author":{"id":"U_kgDOCM71xg","is_bot":false,"login":"JiaaoZheng","name":""},"headRefName":"Fred-UCSBOrganization-Controller","number":59,"title":"Fred ucsb organization controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/59"},{"author":{"id":"U_kgDOCM71xg","is_bot":false,"login":"JiaaoZheng","name":""},"headRefName":"Fred-UCSBOrganization","number":57,"title":"Fred ucsb organization","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/57"},{"author":{"id":"U_kgDOBz88Iw","is_bot":false,"login":"RubenAlvarezGJ","name":"iamruben"},"headRefName":"Ruben-UCSBDiningCommonsMenuItem-delete","number":47,"title":"ra - add DELETE for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/47"}]
