
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-09
owner: ucsb-cs156-s25
repo_name: team01-s25-09
pull_requests: [{"author":{"id":"U_kgDOCM71xg","is_bot":false,"login":"JiaaoZheng","name":""},"headRefName":"Fred-UCSBOrganization","number":57,"title":"Fred ucsb organization","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/57"},{"author":{"id":"U_kgDOB3DxTg","is_bot":false,"login":"moiez12","name":""},"headRefName":"MB-Articles-create-db","number":56,"title":"Mb- Create ArticlesController Get Post ","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/56"},{"author":{"id":"U_kgDOCMMDPQ","is_bot":false,"login":"jasozh5","name":""},"headRefName":"main","number":54,"title":"jason - create database table for MenuItemReview","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/54"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-recreq3","number":53,"title":"AK - add GET by id for RecommendationRequest","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/53"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-recreq2","number":51,"title":"AK - create RecommendationRequest Controller, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/51"},{"author":{"id":"U_kgDOBz88Iw","is_bot":false,"login":"RubenAlvarezGJ","name":"iamruben"},"headRefName":"Ruben-UCSBDiningCommonsMenuItem-delete","number":47,"title":"ra - add DELETE for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/47"},{"author":{"id":"U_kgDOBz88Iw","is_bot":false,"login":"RubenAlvarezGJ","name":"iamruben"},"headRefName":"Ruben-UCSBDiningCommonsMenuItem-put","number":46,"title":"ra - add PUT for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/46"},{"author":{"id":"U_kgDOBz88Iw","is_bot":false,"login":"RubenAlvarezGJ","name":"iamruben"},"headRefName":"Ruben-UCSBDiningCommonsMenuItem-get-by-id","number":45,"title":"ra - add GET by id for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/45"},{"author":{"id":"U_kgDOBz88Iw","is_bot":false,"login":"RubenAlvarezGJ","name":"iamruben"},"headRefName":"Ruben-UCSBDiningCommonsMenuItem-controller","number":44,"title":"ra - create UCSBDiningCommonsMenuItem controller, add  GET /all and POST methods","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/44"}]
