
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-09
owner: ucsb-cs156-s25
repo_name: team01-s25-09
pull_requests: [{"author":{"id":"U_kgDOB3D27Q","is_bot":false,"login":"Jsanchez021","name":""},"headRefName":"Joel-HelpRequest-controller","number":68,"title":"JS - create HelpRequest controller, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/68"},{"author":{"id":"U_kgDOB3D27Q","is_bot":false,"login":"Jsanchez021","name":""},"headRefName":"Joel-HelpRequest-create-db","number":67,"title":"JS - create database table for helprequest","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/67"}]
