
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-09
owner: ucsb-cs156-s25
repo_name: team01-s25-09
pull_requests: [{"author":{"id":"U_kgDOB3DxTg","is_bot":false,"login":"moiez12","name":""},"headRefName":"MB-DeleteArticlesPost","number":65,"title":"MB -  add DELETE for Articles","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/65"},{"author":{"id":"U_kgDOB3DxTg","is_bot":false,"login":"moiez12","name":""},"headRefName":"MB-EditArticles","number":64,"title":"MB - add PUT for ArticlesController","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/64"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-recreq5","number":63,"title":"AK - Delete Controller function for the RecReq database table","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/63"},{"author":{"id":"U_kgDOB3DxTg","is_bot":false,"login":"moiez12","name":""},"headRefName":"MB-GetEndpointSingleRecord","number":62,"title":"MB - add GET (show) endpoint for a single record in Articles table","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/62"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-recreq4","number":61,"title":"AK - PUT(edit/delete) to Controller for the RecommendationRequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-09/pull/61"}]
